//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirportPushPoints
    {
        public long id { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public int heading { get; set; }
        public System.Guid pushbackpathid { get; set; }
    
        public virtual AirportPushBackPath AirportPushBackPath { get; set; }
    }
}
