//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.Strausshome.Yapbt.DataConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirportPositions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AirportPositions()
        {
            this.AirportPushBackPath = new HashSet<AirportPushBackPath>();
        }
    
        public System.Guid positionid { get; set; }
        public string positioname { get; set; }
        public double latitude { get; set; }
        public double longitutde { get; set; }
        public System.Guid variationid { get; set; }
        public System.DateTime cts { get; set; }
    
        public virtual AirportVariations AirportVariations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AirportPushBackPath> AirportPushBackPath { get; set; }
    }
}
