//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.strausshome.yapbt.DataConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempParking
    {
        public long id { get; set; }
        public string Name { get; set; }
        public long Bglid { get; set; }
        public long Number { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    }
}
