//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.Strausshome.Yapbt.DataConnection
{
    public partial class TempParking
    {
        public long id { get; set; }
        public string Name { get; set; }
        public long Index { get; set; }
        public long Number { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    }
}
